const client = require('./client');
// we are requiring the client.js file and storing the exported object in a variable called client.

async function init(){
const result = await client.xadd('mystream', '*', 'name', 'John Doe', 'age', 25);
console.log('result ->', result);
// it gives timestamp of the message.
// why we use * in the second argument?
// * means the id of the message is automatically generated by redis.


// we can use xadd to add a message to a stream.
// the first argument is the name of the stream.
// redis streams are like a list of messages. each message has a unique id. why we use redis streams?
// we can use redis streams to implement a message queue. we can use redis streams to implement a log.
// we can use redis streams to implement a chat application. we can use redis streams to implement a notification system.
// logs means what? logs means a record of events. we can use redis streams to store a record of events.


}
init ()